# Deploy pages
pages:
  stage: deploy
  script:
  # Make bash files executable
  - chmod 755 images.sh
  - chmod 755 indexHTML.sh
  - chmod 755 indexHTML2.sh
  # execute bash files
  - ./indexHTML.sh
  - ./images.sh
  - ./indexHTML2.sh
  # show index.html in pipeline
  - cat index.html
  # show if all files are generated
  - ls -l
  # copy files into public folder
  - mkdir .public
  - cp -r * .public
  - mv .public public
  # Artifacts stores objects that are generated during pipeline and is accessible from the Gitlab Webinterface - if you generate something with the pipeline this is the place to collect it. Or for debug reasons.
  artifacts:
    paths:
    - public
  only:
  - master