# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
  - chmod 777 test.sh
  - chmod 777 indexHTML.sh
  - ./test.sh
  - ./indexHTML.sh
  - cat index.html
  - ls -l
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master